### ISSUE TITLE
Approximate display does not translate

### ISSUE THREAD

**Issue by milotype** [Hanziness/AnotherPomodoro#156]
The text in the "Approximate display" does not translate. See screenshots below:

**2 minutes**
![2 minutes](https://user-images.githubusercontent.com/43657314/149620724-dd815c19-9c08-4d26-9466-92974020b74c.png)

**a minute**
![a minute](https://user-images.githubusercontent.com/43657314/149620735-662bc9e9-19b1-4600-9b31-be9cbdfbd557.png)

**a few seconds**
![a few seconds](https://user-images.githubusercontent.com/43657314/149620750-9cc9ef79-b864-4ddc-95c9-0e6d341f2a2e.png)

**Comment by milotype** [comment]
The texts "one minute" and " a few seconds" do not exist in the translation files.
IMO,
"one minute" should also display as a numeral, like "1 minute".

**Comment by Hanziness** [comment]
Thanks for reporting this! Yes, I've known of this issue. Unfortunately, the translations of the approximate timer are handled by Day.js, an external library (and those are thus not manually translated). I think as a next step I'll implement the translations of these messages myself, so I won't have to rely on a library to do the job.

**Comment by milotype** [comment]
Hmmm ... if you are talking about [Day.js,](https://day.js.org/), at the bottom of the page there is some info:

**I18n**
Day.js has great support for internationalization. But none of them will be included in your build unless you use them.

I have also filed an issue [#1768](https://github.com/iamkun/dayjs/pull/1768) for Croatian.

**Comment by Hanziness** [comment]
Ah, yes, thankfully it was only a matter of importing the locale's files - after #160 the approximate timer is also translated.
