### ISSUE TITLE
Tasks cover start button on narrow screens

### ISSUE THREAD

**Issue by texastoland** [Hanziness/AnotherPomodoro#173]
# Split browser tab (700 x 940)

![Sizzy-Web Panel another-pomodoro app 05Feb 19 42](https://user-images.githubusercontent.com/48431/152640728-9579fd06-7074-44d8-a3a2-24f0ece365b8.png)

# Pixel 5 (393 x 851)

![Sizzy-Pixel 5 another-pomodoro app 05Feb 19 43-1](https://user-images.githubusercontent.com/48431/152640758-2b213276-b1a8-46a6-8162-4f99fd8de175.png)

**Comment by Hanziness** [comment]
Ah yes, thank you! I've known of this and I'm still trying to find a proper way to show the task list on mobile devices. Maybe hiding it under a button (and showing it on click like the settings panel) would make it better. I'll see to it soon :)
