### ISSUE TITLE
Feature: inline editable task titles

### ISSUE THREAD

**Issue by texastoland** [Hanziness/AnotherPomodoro#174]
The current workaround to edit task titles is:

1. delete (I thought the icon meant edit)
2. recreate
3. reorder again

You might be able to use `contenteditable` for a quick implementation:
https://codepen.io/abusedmedia/pen/gZWmLz/

**Comment by Hanziness** [comment]
Cool idea, thank you! Also thank you for bringing up the icon, I'll probably just move back to using the trash can one, that's less ambiguous.
