### ISSUE TITLE
Import export data

### ISSUE THREAD

**Issue by istudyatuni** [Hanziness/AnotherPomodoro#178]
Hello! Thanks for this application!

**Is your feature request related to a problem? Please describe.**

Yes, it would be great to transfer settings from one browser to another (e.g., from my browser to my work browser). Also for backup purposes

**Describe the solution you'd like**

For example, just copy string with settings and then paste it into another browser

**Describe alternatives you've considered**

--

**Additional context**

--

**Comment by Hanziness** [comment]
Thank you for the idea! I'll see what I can do :)

**Comment by Hanziness** [comment]
Sorry for getting back so late with this issue. Saving and restoring settings and tasks was implemented in #228 and should land in version 1.2 soon (it is already on the `develop` branch in case you are self-hosting the app). Hope you'll like it :)
