### ISSUE TITLE
Chinese Simplified Support 

### ISSUE THREAD

**Issue by nmnmcc** [Hanziness/AnotherPomodoro#344]
This is a great project, and I wish I could contribute the Simplified Chinese translation!

**Comment by Hanziness** [comment]
Hello! Thank you very much for your feedback and support! I have added Simplified Chinese to FocusTide's Crowdin page (https://crowdin.com/project/anotherpomodoro/zh-CN)!

**Comment by nmnmcc** [comment]
![image](https://user-images.githubusercontent.com/64564727/226097049-f650e5f8-f0ca-4f50-9df8-3588a67c762b.png)
❤️

**Comment by Hanziness** [comment]
Thank you so much for your help, @huangyinhaow! I approved your translations, version 1.5 will include them :)

I'll reopen the issue until the changes are merged as I'll have to include an additional line for the translations to be enabled.

**Comment by Hanziness** [comment]
Sorry for taking so long with this, I have one final question before merging and enabling the language. Is it correct to write "简体中文" as the language's name in the language picker? It would look like this:

![Screenshot of the updated language picker with Simplified Chinese](https://github.com/Hanziness/FocusTide/assets/18259108/af5ffd6e-7dca-4193-ae51-0c9db1c39f38)

**Comment by nmnmcc** [comment]
You are right!
