### ISSUE TITLE
Feature suggestion: Auto start breaks/ pomodoros

### ISSUE THREAD

**Issue by KNN-07** [Hanziness/AnotherPomodoro#348]
First of all, really appreciate your dedication to such a beautiful and useful app!
I think a option for user to auto start pomodoros/ breaks sessions would be nice.
Like what [Pomofocus](https://pomofocus.io/) does might works?

**Comment by Hanziness** [comment]
I'm so sorry for not replying and implementing it earlier, I believe the functionality added in #361 should allow you to do this. While the implementation doesn't allow you to set this behavior separately for work/pause sections, you can choose whether (a) the timer of the current section keeps going, (b) the next section starts automatically, or (c) the timer stops when it ends.

If it is not what you think, feel free to add another comment and I'll reopen the issue. In the coming weeks/months, I won't have much time to work on new features, but I'll try to make some time to keep the app updated :)

**Comment by KNN-07** [comment]
> I'm so sorry for not replying and implementing it earlier, I believe the functionality added in #361 should allow you to do this. While the implementation doesn't allow you to set this behavior separately for work/pause sections, you can choose whether (a) the timer of the current section keeps going, (b) the next section starts automatically, or (c) the timer stops when it ends.
> 
> If it is not what you think, feel free to add another comment and I'll reopen the issue. In the coming weeks/months, I won't have much time to work on new features, but I'll try to make some time to keep the app updated :)

Really appreciate your work 🙏
