### ISSUE TITLE
Internationalization, localization

### ISSUE THREAD

**Issue by Hanziness** [Hanziness/AnotherPomodoro#4]
The app could handle multiple locales (this is mostly relevant to the settings modal and the approximate timer). The Day.js integration could make this a bit more difficult.

**Comment by ghost** [comment]
It would be cool to integrate with similar services like [Crowdin](https://crowdin.com/).

**Comment by Hanziness** [comment]
Absolutely! I've already created and set up a project on Crowdin, I'll share it in the repo soon.
